[experimentalDesign]

# release function: ANN flow adjustment [adjANN], ANN flow release [fANN], rule curve [RC]
releaseFunction = "adjANN"

# flow limits: Bv7 without deviations [Bv7], Plan 2014 with deviations [2014]
limitType = "Bv7"

# september rule: on, off
septemberRule = "off"

# forecast lead-time: 12month, 6month, 3month, 1month
forecastLeadTime = "12month"

# forecast skill: 12-month status quo AR(1) [sqAR], linear model [sqLM], perfect [0]
forecastSkill = "sqLM"

# number of decision variables
numDV = 61

# number of objectives
numObj = 7

# number of constraints
numCon = 0

# trace to simulate
trace = "historic"

# number of function evaluations
nfe = 25000

# initial population size
popSize = 100

# frequency of function evaluations to report metrics
metFreq = 100

[decisionVariables]
dvName = [
    'M1N1',
    'M2N1',
    'M1N2',
    'M2N2',
    'M1N3',
    'M2N3',
    'M1N4',
    'M2N4',
    'M1N5',
    'M2N5',
    'M1N6',
    'M2N6',
    'M1N7',
    'M2N7',
    'M1N8',
    'M2N8',
    'M1N9',
    'M2N9',
    'M1N10',
    'M2N10',
    'M1N11',
    'M2N11',
    'M1N12',
    'M2N12',
    'M1N13',
    'M2N13',
    'M1N14',
    'M2N14',
    'M1N15',
    'M2N15',
    'N1B',
    'N2B',
    'N3B',
    'N4B',
    'N5B',
    'N6B',
    'N7B',
    'N8B',
    'N9B',
    'N10B',
    'N11B',
    'N12B',
    'N13B',
    'N14B',
    'N15B',
    'N1O1',
    'N2O1',
    'N3O1',
    'N4O1',
    'N5O1',
    'N6O1',
    'N7O1',
    'N8O1',
    'N9O1',
    'N10O1',
    'N11O1',
    'N12O1',
    'N13O1',
    'N14O1',
    'N15O1',
    'O1B',
]
lowerBounds = [
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
    -10,
]
upperBounds = [
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
]
normalizedRange = [0, 1]

[performanceIndicators]
metricWeighting = 'netAnnualAverage'
piName = [
    "Coastal Impacts: Upstream Buildings Impacted (#)",
    "Coastal Impacts: Downstream Buildings Impacted (#)",
    "Commercial Navigation: Ontario + Seaway + Montreal Transportation Costs ($)",
    "Hydropower: Moses-Saunders + Niagara Energy Value ($)",
    "Meadow Marsh: Area (ha)",
    "Muskrat Lodge Viability (%)",
    "Recreational Boating: Impact Costs ($)",
]
epsilonValue = [1700.0, 110.0, 0.98e6, 112e6, 500.0, 4.5, 1e6]
direction = ["min", "min", "min", "max", "max", "max", "min"]

